// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "9eabb532-5128-4168-bc7c-2f0a819ebb43");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1784826311);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1784826310);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1784826308);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "6da43b61-beea-4e9d-aa48-5fbba2c1ba8a");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1784826305);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.ipProtection.added", true);
user_pref("browser.ipProtection.enabled", true);
user_pref("browser.ipProtection.stateCache", "unauthenticated");
user_pref("browser.ipProtection.usageCache", "");
user_pref("browser.migration.version", 172);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v4:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.discoverystream.merino-provider.ohttp.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs", "newtab_stories_1, newtab_stories_2, newtab_stories_3, newtab_stories_4, newtab_stories_5, newtab_stories_6, newtab_stories_7, newtab_stories_8, newtab_stories_9, newtab_stories_10, newtab_stories_11, newtab_stories_12");
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs.counts", "1,1,1,1,1,1,1,1,1,1,1,1");
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.interestPicker.visibleSections", "top_stories_section,tv,photojournalism,featured-videos,arts,small-wins,in-conversation,travel,explained,government,nba,by-the-numbers,in-the-zeitgeist,home,society-parenting,nhl,business,nfl,long-reads,hobbies");
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.personalization.inferred.enabled", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{90844586-3773-4ddc-aa6e-a5c3f259abb8}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.activity-stream.telemetry.privatePing.inferredInterests.enabled", true);
user_pref("browser.newtabpage.activity-stream.telemetry.surfaceId", "NEW_TAB_EN_US");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "154.8.20260716.43450");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1784826301);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1784826314986");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1784847914986");
user_pref("browser.search.region", "US");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.startup.lastColdStartupCheck", 1784826310);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1784826307);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"ipprotection-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ipprotection-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1784826);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "7f66f6e4-54c5-48b4-b197-e36e1a2f4385");
user_pref("datareporting.dau.cachedUsageProfileID", "cd69c6ca-3b9d-401e-9580-a9011b13293c");
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", true);
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "152.0.6");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "5514fcf410b444cdb2718c2d61b23ead");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260714090335");
user_pref("extensions.lastAppVersion", "152.0.6");
user_pref("extensions.lastPlatformVersion", "152.0.6");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"d1c2aa14-bf66-4fd7-99ca-5779329f644c\",\"formautofill@mozilla.org\":\"cb23a815-b966-465d-92e0-a1ab2c55586b\",\"ipp-activator@mozilla.com\":\"c787cc5f-a290-4117-b189-027190c8249c\",\"pictureinpicture@mozilla.org\":\"85a260dd-dafe-4715-8d8b-d089ac898bf8\",\"addons-search-detection@mozilla.com\":\"eb4480de-06d8-4c85-a3df-ac5281063a18\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"d35a6ef1-d2e3-40c3-81a7-b34cdde13a09\",\"default-theme@mozilla.org\":\"05f6295d-67a9-4027-9f30-4b74d479878b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "bad4ebe8-0414-4f46-8799-a2bb48027427");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks");
user_pref("sidebar.nimbus", "upgraded-sidebar-rollout-without-messaging:rollout-treatment");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.revamp", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("termsofuse.bypassNotification", true);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "1b5bc7fc");
user_pref("toolkit.startup.last_success", 1784826297);
user_pref("toolkit.telemetry.cachedClientID", "db4952eb-e0a6-4be4-ac24-e7284522767b");
user_pref("toolkit.telemetry.cachedProfileGroupID", "7919ac25-b304-4c72-8dca-41d721adb25a");
user_pref("toolkit.telemetry.previousBuildID", "20260714090335");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
