// Generated by CIRCT firtool-1.47.0
module Dff(
  input        clock,
               reset,
  input  [7:0] io_d,
  input        io_enable,
  output [7:0] io_q
);

  reg [7:0] q;
  always @(posedge clock) begin
    if (reset)
      q <= 8'h0;
    else if (io_enable)
      q <= io_d;
  end // always @(posedge)
  assign io_q = q;
endmodule

