name: "00-000-dff regression (make all)"

on:
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  make-all:
    uses: chiselWare/ci-workflows/.github/workflows/make-all.yml@v1
    with:
      module_name: "dff"
      make_target: "all"
      runner_labels: '["self-hosted","local-ci"]'
    secrets: inherit
